apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tomcat
  namespace: argocd  
spec:
  project: default    
  source:
    repoURL: https://github.com/umamaheswaritalupuri/new.git   
    targetRevision: main                             # Branch, tag, or commit
    path: folder1                          # Path inside repo
  destination:
    server: https://kubernetes.default.svc            # Cluster API server
    namespace: tomcat                           # Target namespace
  syncPolicy:
    automated:                                        # Optional: enable auto-sync
      prune: true                                     # Remove resources not in Git
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
